
# Fonts
#font=Consolas
#logotext={\\1c&HFFFFFF\\bord0\\fs28\\fn微软雅黑 light\\fscx125}mpv

# Timing
fadeduration=500
hidetimeout=100

# Scaling

# Do not scale by window size
vidscale=no
scalewindowed=1.0
scalefullscreen=1.0
scaleforcedwindow=1.0

# Interface
deadzonesize=1.0
seekbarhandlesize=3.5
boxalpha=110
seekrangealpha=180
buttonalpha=40
showchaptertooltip=yes